# Generated by Django 3.1.2 on 2021-03-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, related_name='bikes', to='bikes.Detail'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='robbed_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
