# Generated by Django 3.1.2 on 2021-03-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20210317_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='details',
            field=models.ManyToManyField(blank=True, related_name='bikes', to='bikes.Detail'),
        ),
    ]
