# Generated by Django 3.1.2 on 2021-03-18 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20210318_0138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Trait',
        ),
    ]
