# Generated by Django 3.1.2 on 2021-03-18 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20210318_0209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='details',
            new_name='traits',
        ),
    ]
