# Generated by Django 3.1.2 on 2020-12-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikeowner', '0007_auto_20201209_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coords', models.JSONField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bikeowner.bike')),
            ],
        ),
    ]
