# Generated by Django 3.1.2 on 2020-10-14 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bike',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bikeowner.bike', verbose_name='details'),
        ),
    ]
