# Generated by Django 3.1.2 on 2020-11-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='url_key',
            field=models.CharField(default='R5EEZ5', max_length=255, unique=True),
        ),
    ]
