# Generated by Django 3.1.2 on 2020-10-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0002_auto_20201014_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='robbed_location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='url_key',
            field=models.CharField(default='11B0BJROKB', max_length=255, unique=True),
        ),
    ]
