# Generated by Django 3.1.2 on 2020-11-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0002_auto_20201119_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='url_key',
        ),
    ]
