# Generated by Django 3.1.2 on 2020-12-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0005_auto_20201203_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='picture',
            field=models.ImageField(null=True, upload_to='bikes/'),
        ),
    ]
