# Generated by Django 3.1.2 on 2020-12-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikeowner', '0006_bike_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='picture',
            field=models.ImageField(default='bikes/default.jpg', max_length=255, null=True, upload_to='bikes/'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
